#refer to the e3sm confluence page for more details of the workflow

#This workflow assumes that the mesh_only workflow has already been run
#and all preprocessing (river network, watershed boundary, coastline) is complete.
#This workflow uses the existing mesh and preprocessed data to run pyflowline.

import os
from datetime import datetime
from shutil import copy2

from pyflowline.configuration.read_configuration_file import pyflowline_read_configuration_file
from pyflowline.configuration.change_json_key_value import change_json_key_value

##======================================================================
# The only thing you need to change for different runs is the settings below
# start of user settings
##======================================================================
#date time for simulation
sDate_today = '20260302'  #use a fixed date for easy repeatability
sDate_today = datetime.now().strftime('%Y%m%d')
#index for different runs
iCase_index = 1

#resolution settings (must match the mesh_only workflow)
dResolution_ocean = 30
dResolution_land = 12  #unit in km
dResolution_river_network = 6.0
dResolution_coastline = 6.0  #unit in km

#number of largest outlet to be processed (must match the mesh_only workflow)
nOutlet_largest = 100

#workspace paths
sWorkspace_output = '/compyfs/liao313/04model/pyhexwatershed/global/'

#preprocessed data paths (from mesh_only workflow)
sWorkspace_river_network_output = '/compyfs/liao313/04model/pyhexwatershed/global/river_network'
sWorkspace_watershed_boundary_output = '/compyfs/liao313/04model/pyhexwatershed/global/watershed_boundary'
sWorkspace_coastline_output = '/compyfs/liao313/04model/pyhexwatershed/global/coastline'

#existing mesh file (generated by mesh_only workflow)
sFilename_mpas_mesh_netcdf = '/compyfs/liao313/04model/pyhexwatershed/global/pyflowline20251122001/jigsaw/out/invert_mesh.nc'

##======================================================================
# end of user settings
##======================================================================

sMesh_type = 'mpas'

#calculate thresholds (must match mesh_only workflow)
dThreshold_area_island = dResolution_ocean * dResolution_ocean * 10 * 1.0E6
dResolution_coastline_buffer = dResolution_coastline * 1.0E3
dDrainage_area_threshold = dResolution_land * dResolution_land * 100 * 1.0E6

#string format for file names
dDistance_tolerance = dResolution_river_network * 1.0E3
sDistance_tolerance = "{:.2E}".format(dDistance_tolerance)
sDrainage_area_threshold = "{:.2E}".format(dDrainage_area_threshold)
sCoastline_buffer = "{:.1E}".format(dResolution_coastline_buffer)
sThreshold_area_island = "{:.1E}".format(dThreshold_area_island)

#construct paths to preprocessed data
sWorkspace_river_network_output = os.path.join(sWorkspace_river_network_output, sDistance_tolerance + '_' + sDrainage_area_threshold)
sWorkspace_watershed_boundary_output = os.path.join(sWorkspace_watershed_boundary_output, sDistance_tolerance + '_' + sDrainage_area_threshold)
sWorkspace_coastline_output = os.path.join(sWorkspace_coastline_output, sCoastline_buffer + '_' + sThreshold_area_island)

print('Using preprocessed data from:')
print('  River network:', sWorkspace_river_network_output)
print('  Watershed boundary:', sWorkspace_watershed_boundary_output)
print('  Coastline:', sWorkspace_coastline_output)

#reference to preprocessed files
sFilename_pyflowline_configuration = os.path.join(sWorkspace_river_network_output, 'pyflowline_configuration.json')
sFilename_pyflowline_configuration_basins = os.path.join(sWorkspace_river_network_output, 'pyflowline_configuration_basins.json')
sFilename_vector_coastline_merged = os.path.join(sWorkspace_coastline_output, 'land_ocean_mask_wo_island_merged.geojson')

#verify that preprocessed files exist
if not os.path.exists(sFilename_pyflowline_configuration):
    raise FileNotFoundError(f"Configuration file not found: {sFilename_pyflowline_configuration}\nPlease run the mesh_only workflow first.")
if not os.path.exists(sFilename_pyflowline_configuration_basins):
    raise FileNotFoundError(f"Basin configuration file not found: {sFilename_pyflowline_configuration_basins}\nPlease run the mesh_only workflow first.")
if not os.path.exists(sFilename_vector_coastline_merged):
    raise FileNotFoundError(f"Coastline file not found: {sFilename_vector_coastline_merged}\nPlease run the mesh_only workflow first.")
if not os.path.exists(sFilename_mpas_mesh_netcdf):
    raise FileNotFoundError(f"Mesh file not found: {sFilename_mpas_mesh_netcdf}\nPlease run the mesh_only workflow first or update the path.")

#run the pyflowline workflow with existing mesh
try:
    #copy the template configuration file to the output directory
    change_json_key_value(sFilename_pyflowline_configuration, "sWorkspace_output", sWorkspace_output)
    oPyflowline = pyflowline_read_configuration_file(sFilename_pyflowline_configuration,
                                                      iCase_index_in=iCase_index,
                                                      sDate_in=sDate_today)
    sWorkspace_output_case = oPyflowline.sWorkspace_output

    #copy configuration files to output directory
    sFilename_configuration_copy = os.path.join(sWorkspace_output_case, 'pyflowline_configuration_copy.json')
    copy2(sFilename_pyflowline_configuration, sFilename_configuration_copy)

    sFilename_configuration_basins_copy = os.path.join(sWorkspace_output_case, 'pyflowline_configuration_basins_copy.json')
    copy2(sFilename_pyflowline_configuration_basins, sFilename_configuration_basins_copy)

    #update the configuration file with our own settings
    change_json_key_value(sFilename_configuration_copy, "iFlag_simplification", 0) #disable flowline simplification
    change_json_key_value(sFilename_configuration_copy, "iFlag_create_mesh", 1)
    change_json_key_value(sFilename_configuration_copy, "iFlag_global", 1)
    change_json_key_value(sFilename_configuration_copy, "iFlag_run_jigsaw", 0) #use existing mesh, don't run jigsaw
    change_json_key_value(sFilename_configuration_copy, "iFlag_intersect", 1) #turn on intersection
    change_json_key_value(sFilename_configuration_copy, "sFilename_coastline_boundary", sFilename_vector_coastline_merged)
    change_json_key_value(sFilename_configuration_copy, "sFilename_mpas_mesh_netcdf", sFilename_mpas_mesh_netcdf) #use existing mesh
    change_json_key_value(sFilename_configuration_copy, "iFlag_force_watershed_boundary", 1)
    change_json_key_value(sFilename_configuration_copy, "sFilename_basins", sFilename_configuration_basins_copy)

    #set up pyflowline to run with the existing mesh
    oPyflowline = pyflowline_read_configuration_file(sFilename_configuration_copy,
                                                      iCase_index_in=iCase_index,
                                                      sDate_in=sDate_today,
                                                      sMesh_type_in=sMesh_type)

    oPyflowline._pyflowline_create_hpc_job(sSlurm_in='slurm', hours_in=8)
    print('HPC job script created successfully!')
    print('Output directory:', sWorkspace_output_case)
    print('Please submit the job manually.')

except Exception as e:
    print(f"An error occurred: {e}")
    raise

print('Workflow setup completed successfully!')
print('Output directory:', sWorkspace_output_case)
